config/routes.rb
Rails.application.routes.draw do
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  resources :articles, only: [:new, :index, :edit, :update, :show]
  resources :videos, only: [:new, :index, :edit, :update, :show]
  resources :galeries, only: [:index, :show]
  # get 'articles/new'
  post 'articles/create'
  post 'videos/create'

  post 'oeufs/create'
  # get 'articles/index'
  # get 'articles/show'
  get 'suggestions/new'
  post 'suggestions/create'
  get 'suggestions/show'
  get 'suggestions/index'

  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'galerie', to: 'pages#galerie', as: :galerie


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/galerie.rb
class Galerie < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_tags, against: :tags
end

app/models/oeuf.rb
class Oeuf < ApplicationRecord
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
    @article.save!
    redirect_to articles_path, notice:"Nouvel Article ajouté, bien ouej!"
  end
  def edit
    @article = Article.find(params[:id])
  end
  def update
  	@article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def index
    @articles = Article.all.sort_by{|e| e[:time_ago]}.reverse()
  end

  def show
    @article = Article.find(params[:id])

  end


  private

  def article_params
  	params.require(:article).permit(:id, :title, :text, :address, :author, :numbers_of_characters, :photo, :date, :slug, :meta_title, :meta_image, :meta_description)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  end

  def unacceptable
    respond_to do |format|
      format.html { render status: 422 }
    end
  end

  def internal_error
    respond_to do |format|
      format.html { render status: 500 }
    end
  end
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
	skip_before_action :authenticate_user!
	def index
    if params[:galeries].present?
      @galeries = Galerie.search_by_tags(params[:galeries])
    else
		  @galeries = Galerie.all
    end
	end

	def show
		@galerie = Galerie.find(params[:id])
	end


  private

  def galerie_params
  	params.require(:galerie).permit(:id, :nom, :metadescription, :metatitre, :url)
  end
end

app/controllers/oeufs_controller.rb
class OeufsController < ApplicationController
  skip_before_action :authenticate_user!


  def new
    @oeuf = Oeuf.new
  end

  def create
    @oeuf = Oeuf.new
    @oeuf.save!
    redirect_to dashboard_path, notice:"Nouvel Oeuf ajouté, bien ouej!"
  end
  private

  def oeuf_params
    params.require(:oeuf).permit(:id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :galerie, :videos ]

  def home
  	    @suggestion = Suggestion.new
        @last_images = Galerie.last(3).reverse()
        @last_articles = Article.last(3).reverse()
        @oeuf = Oeuf.new

  end

  def galerie

  		results = Cloudinary::Api.resources_by_tag("Viivan", max_results: 100)
  		jon = results.first[1]
  		@cloudinary_viivan_images = jon

  end
  def dashboard
  	@suggestions = Suggestion.all
  	@articles = Article.all
    @oeuf = Oeuf.new(count: "blabla")
  end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  	@suggestion = Suggestion.new
  end

  def create
  	@suggestion = Suggestion.new(suggestion_params)
    if @suggestion.save
      redirect_to root_path(anchor: "suggestions"), notice:"Nous avons bien reçu votre suggestion, merci pour votre aide !"

    else
      render :new
    end
    # respond_to do |format|
    #   format.js { flash[:notice] = "Created order" }
    # end

  end

  def show
  end

  def index
    @suggestions = Suggestion.all
  end

  private

  def suggestion_params
  	params.require(:suggestion).permit(:name_owner, :email_owner, :name_contact, :email, :phone_number, :address, :code_postal, :ville, :description, :category)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
   skip_before_action :authenticate_user!, only: [ :index, :show ]

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.save!
    redirect_to videos_path, notice:"Nouvelle Video ajouté, bien ouej!"
  end

  def edit
    @video = Video.find(params[:id])
  end
  def update
    @video = Video.find(params[:id])
    @video.update(video_params)

    redirect_to video_path(@video)
  end

  def index
    @videos = Video.all.sort_by{|e| e[:time_ago]}.reverse()
  end

  def show
    @video = Video.find(params[:id])

  end


  private

  def video_params
    params.require(:video).permit(:id, :title, :url, :slug, :meta_title, :meta_image, :meta_description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/articles/new.html.erb
<div class="banner-articles-index">
	<div class="container">
		<%= simple_form_for @article, url: articles_create_path do |f| %>
			    <div class="form-inputs">
			    <h2>Remplis ici ton article</h2>
			    <%= f.input :title, required: true, placeholder: 'Titre de l\'article', label: false%>
			    <%= f.input :date, required: true, placeholder: 'Date', label: false %>
			    <br>
			    <%= f.input :address, required: true, placeholder: 'Adresse', label: false%>
			    <%= f.input :duration, required: true, placeholder: 'Temps de lecture', label: false  %>
			    <%= f.input :photo, required: true, placeholder: 'Photo', label: false  %>
			    <%= f.input :text, required: true, placeholder: 'Texte', label: false  %>
			    <%= f.input :author, :as => :select, :prompt => 'Auteur', collection: ['Céline Devinoy', 'Baptiste Chebassier', 'Céline Devinoy et Baptiste Chebassier', 'Autre'], label: false %><br>
			  	<h3>Meta-Informations (propre à chaque article)</h3>
			    <%= f.label :slug,'Slug (c\'est la partie url après le  en général c\'est mieux d\'avoir le nom de l\'article (il ne faut pas d\'accents non plus ou d\'espace)'  %>
			     <%= f.input :slug, required: true, placeholder: 'Slug', label: false  %>
			    <%= f.input :meta_title, required: true, placeholder: 'Meta-title', label: false  %>
			    <%= f.input :meta_description, required: true, placeholder: 'Meta-description', label: false  %>
			    <%= f.input :meta_image, required: true, placeholder: 'Idéalement mettre l\'url de l\'image cloudinary', label: false  %>
			  </div>

			  <div class="form-actions">
			    <%= f.button :submit, "Valider l'article", class: "btn btn-primary full-width" %>
			  </div>

		<% end %>

	</div>

</div>

app/views/galeries/_galeries.html.erb
<% galeries.each do |image| %>
  <%= link_to galery_path(image) do %>
          <%#= image_tag(image["url"], class: "image-galerie") %>
          <%= cl_image_tag(image["nom"],
    :transformation=>[{:raw_transformation=> "w_300"}], class: "image-galerie")%>

<% end %>

app/views/galeries/index.html.erb
<div class="banner-galerie">
	<div class="container">
    <div class="grid d-flex justify-center">
      <!-- <div class="buttons">
        <ul class="btn btn-danger click-me" >Michelle</ul>
      </div> -->
      <%= form_tag galeries_path, method: :get, class: "galerie-form" do %>
         <h3>Que voulez-vous voir ? </h3>
         <br>

          <%= select_tag :galeries, options_for_select(["Viivan", "Bapt&Céline", "Elvis", "landscape", "Michèle&Jeanine", "work&move"], params[:galeries]), id: "different_option_value_html", onchange: "this.form.submit();", class: "galerie-select" %>

      <%end%>
    </div>

		<div class="grid">
		<% @galeries.each do |image| %>
			<%= link_to galery_path(image) do %>
					<%#= image_tag(image["url"], class: "image-galerie") %>
          <%= cl_image_tag(image["nom"],
    :transformation=>[{:raw_transformation=> "w_300"}], class: "image-galerie")%>


				<%end%>
		<% end %>
		</div>
<!-- 			<#% @cloudinary_viivan_images.each do |image| %>
				<#%= link_to image["url"] do %>
					<#%= image_tag(image["url"], class: "image-galerie") %>

				<#%end%>
			<#%	end %> -->

	</div>

</div>

app/views/galeries/show.html.erb
<div class="container">
	<div class="wrapper">
		<div class="left-show">
			<div class="left-arrow arrow">
				<% if @galerie[:id] > 0  %>
					<%= link_to " < ",galery_path(params[:id].to_i - 1)%>
				<% end %>
			</div>

			<%= link_to "", galeries_path %>
		</div>
		<div class="image">
			<%#= image_tag(@galerie[:url], class: "image-show") %>
      <%= cl_image_tag(@galerie["nom"],
    :transformation=>[{:raw_transformation=> "w_1000"}], class: "image-show")%>
		</div>
			<!-- <div class="infos-show">

				<div class='infos-show-content'>
					<div class="number col-3 align-middle"> <p> <%#=@galerie.numéro %></p>
					</div>
					<div class="infos-right col-9">
						<div class=" table-cell">
							<div class="titre col-12"><%#=@galerie.titre %></div>
							<div class="details col-12"><#%=@galerie.details %></div>
							<div class="dimensions col-12"><#%=@galerie.dimensions %></div>

						</div>
					</div>
				</div>
			</div>		 -->
		<div class="right-show">
			<%= link_to "",galeries_path %>
			<div class="right-arrow arrow">
				<% last = Galerie.count - 1 %>
				<% if @galerie[:id] = last %>
					<%=  link_to " > ",galery_path(params[:id].to_i + 1)  %>
				<% end %>

<!-- 					<#%= link_to " > " ,jeanpierrechebassier_path %>
				<#% else %>
					<#% suivant = @galerie[:id] + 1] %>
					<#% jonny = Galerie.find(:id = suivant)
					<#%= link_to " > ",galery_path(@galerie[:id + 1])%>
				<#% end %>  -->
			</div>
		</div>

	</div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="banner-dashboard">
  	<h1>Dashboard Admin</h1>
    <div class="egg-content">
      <div class="row">
        <h2>Nombre d'oeufs : <%=Oeuf.count %></h2>


      </div>

      <div class="new-egg">
        <%= simple_form_for @oeuf, url: oeufs_create_path do |f| %>
            <div class="form-actions">
            <%= f.button :submit, "Ajouter un nouvel oeuf", class: "btn btn-primary full-width" %>
            </div>
        <% end %>
      </div>

  	<div class="suggestion-content">
  		<h2>Suggestions</h2>
  		<div class="dashboard-suggestions">
  			<% @suggestions.each do |suggestion| %>
  			<div class="dash-suggestion">
  				<h3 class="text-center"><%= suggestion.ville %></h3>
  				<div class="dash-owner">
  					<p>Par : <%= suggestion.name_owner %></p>
  				 	<p>Email : <%= suggestion.email_owner %></p>
  				</div>
  				<br>
  				<div class="dash-contact">
  					<h4>Contact</h4>
  					<p> Nom du contact : <br><strong><%= suggestion.name_contact %>  </strong></p>
  					<p> Adresse : <br> <strong><%= suggestion.address %> </strong> </p>
  					<p> Ville : <br> <strong><%= suggestion.ville %> </strong> </p>
  					<p> Code Postal : <br> <strong><%= suggestion.code_postal %> </strong> </p>
  					<p> Numéro de tel : <br> <strong><%= suggestion.phone_number %>  </strong></p>
  					<p> Email : <br> <strong><%= suggestion.email %> </strong> </p>
  					<p> Description : <br> <strong><%= suggestion.description %> </strong> </p>
  					<p> Categorie : <br> <strong><%= suggestion.category %> </strong> </p>

  				</div>
  			</div>
  			<% end %>
  		</div>

  	</div>
  	<div class="dashboard-articles">
      <h2>Nombre d'articles : <%=Article.count%></h2>
      <% @articles.each do |article| %>

      <%end %>

  	</div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="banner banner-absolute" id="banner">
	<div class="content-banner active" >
		<%= image_tag("viivan.gif", :class => "viivan-gif", :id => 'viivan-gif') %>
	</div>

	<div class="container" id="container">
    <div class="offset-md-2 col-md-8">

  		<div class="titre justify-center">
  			<h1><span>SUR LA ROUTE</span></h1>
  			<h2 class="text-center">À la rencontre de la France, des vivants et du vivant.</h2>
  		</div>
  		<div class="explications">
  			<p>Fraîchement diplômés, Céline de Sciences Sociales et Baptiste en Management de l'Innovation, nous avons décidé de partir à l'avanture en essayant un nouveau moyen de transport pour nous : le van aménagé. Camping-car mieux looké, celui-ci a l'avantage de passer un peu plus inaperçu, et d'attirer la sympathie des gens rencontrés. Nous avons ainsi choisi d'embarquer à bord du petit Elvis : 3,5 tonnes, 4m de long et 2,8m de haut.
  		<br>
  			Nous souhaitons découvrir un mode de vie plus simple, itinérant, supprimant autant que possible le superflu que nous avons eu l'habitude d'accumuler dans notre quotidien. L'objectif étant de retrouver du confort avec le minimum.  <br><br><strong> Dans le van : pas de chauffage, pas d'eau chaude, pas de douche, pas de toilettes. 10 euros par jour par personne. </strong>
  		<br><br>
  	        Sortir de notre zone de confort c'est aussi provoquer la rencontre avec les individus qui vont se trouver sur notre chemin et apprendre un maximum de nouvelles choses sur le monde qui nous entoure, le monde vivant.

  	        Avancer, découvrir, s'émerveiller, rencontrer, apprendre, c'est ce que l'on s'apprête à vivre durant les prochains mois avec Elvis !
  		</div>
    </div>

		<div class="video">

      <iframe src="https://player.vimeo.com/video/595190592?h=d335fd2bef" width="1280" height="720" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="VIIVAN - mars 2021"></iframe>
		</div>
		<div class="suivez-nous" id="suivez-nous">
			<h3><span>Suivez-nous !</span></h3>
			<div class="row">
				<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1ZRhiosmTJX9BQw91Dj4vNBUC9HIMfG_n" width="640" height="480" class="col-md-9"></iframe>
				<p class="col-md-3">Vous trouverez ici toutes les étapes où nous avons dormi jour après-jour. Il vous suffit de cliquer sur une position épinglée pour y trouver un petit résumé et une photo.</p>

			</div>
		</div>
		<div class="suggestions" id="suggestions">
			<h3><span>Des Suggestions ?</span></h3>

						<p>Vous pouvez ici nous proposer vos lieux préférés, perles rares, découvertes, mais aussi vos contacts insolites, et/ou contacts qui selon vous nous permettront d'en apprendre toujours plus sur la vie :) <br> Nous gardons toutes les infos de contact pour nous et indiquerons juste la ville du lieu sur une carte accessible à tous ! </p>
			<div class="row">
				<div class="col-md-8 d-flex justify-content-center">
						<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1LVmNtCqxSiL7es9bs7-lMSlWa-WM3dZI" width="550" height="500" style="margin-top: 90px;"></iframe>
				</div>
				<div class="col-md-4">

					<%= simple_form_for @suggestion, url: suggestions_create_path, class: 'col-3' do |f| %>
				      <div class="form-inputs">
				        <h3>Qui êtes vous ?</h3>
				        <%= f.input :name_owner, required: true, placeholder: 'Nom complet', label: false%>
				        <%= f.input :email_owner, required: true, placeholder: 'Email ou numéro de téléphone', label: false %>
				        <br>
				        <h3>Un contact, lieu à nous proposer ?</h3>
				        <%= f.input :name_contact, required: true, placeholder: 'Nom complet du contact / lieu', label: false%>
				        <%= f.input :address, required: true, placeholder: 'Numéro + rue', label: false  %>
				        <%= f.input :code_postal, required: true, placeholder: 'Code postal', label: false  %>
				        <%= f.input :ville, required: true, placeholder: 'Ville', label: false  %>
				        <%= f.input :email, required: true, placeholder: 'Email', label: false  %>
				        <%= f.input :phone_number, required: true, placeholder: 'Numéro de téléphone', label: false  %>
				        <%= f.input :description, required: true, placeholder: 'Description', label: false  %>
				        <%= f.input :category, :as => :select, :prompt => 'Catégorie', collection: ['Sport', 'Ferme', 'Arts', 'Artisanat', 'Insolite', 'Culture', 'Nature'], label: false %><br>
				      </div>

				      <div class="form-actions offset-sm-1 col-sm-10 offset-md-2 col-md-8">
				        <%= f.button :submit, "Valider", class: "btn btn-primary full-width col-12" %>
				      </div>

				    <% end %>

				</div>
			</div>


		</div>
		<div class="banner-articles">
			<h3><span>Nos derniers articles</span></h3>
			<p>Nous écrivons des articles racontant des anecdotes de notre périple, moments forts qui nous auront marqué l'esprit, pour les partager avec nos proches et tous les curieux qui le souhaitent. Aussi une manière de créer un carnet de voyage virtuel et de garder une trace de notre aventure. </p>
			<div class="articles" id="articles">
				<% @last_articles.each do |article| %>
				<%= link_to(article_path(article), class: 'article') do |f| %>

					<div class="content-photo">
						<%#= image_tag(article.photo, :class => "photo-article") %>
            <%= cl_image_tag(article.photo,
    :transformation=>[{:raw_transformation=> "w_300"}], class: "photo-article")%>
					</div>
					<div class="article-titre">
						<h2><span>	<%= article.title %></span></h2>
						<!-- <p><#%= article.meta_description %> </p> -->
					</div>

					<% end %>
				<% end %>
			</div>
			<div class="btn-wrapper">
				<%= link_to "Voir tous les articles", articles_url, class:('btn-blue') %>
			</div>
		</div>
		<div class="galerie" id="galerie">
			<h3><span>Découvrez nos dernières photos !</span></h3>
			<div class="grid">
				<% @last_images.each do |image| %>

          <%= link_to galery_path(image) do %>
            <%= cl_image_tag(image["nom"], :transformation=>[{:raw_transformation=> "w_400"}])%>

          <%end%>
				<% end %>


			</div>
			<div class="btn-wrapper">
				<%= link_to "Voir toutes les photos", galeries_url, class:('btn-blue') %>
			</div>



		</div>
		<div class="banner-team">
			<h3><span>Qui sommes-nous?</span> </h3>
			<p>Céline et Baptiste, nous avons 23 et 24 ans et avons décidé de partir voyager en France après nos études pour découvrir le plus beau pays du monde : le nôtre. </p>
			<div class="row">
				<div class="baptiste member col-md-6">
					<div class="image-team">

						<%= cl_image_tag("Viivan/BaptFichier_10.png",:transformation=>[{:raw_transformation=> "w_300"}]) %>
					</div>
					<h4>Baptiste Chebassier</h4>
					<p>Je suis un doux rêveur, qui a des milliers de projets (dans ma tête) et j'essaye d'en concrétiser quelques uns. Malgré que je dois toujours avoir un avis différent, je suis toujours partant pour apprendre le plus possible et partir à l'aventure ! J'ai d'autant plus la chance de partager celle-ci avec la merveilleuse <strong>❤ Céline ❤ </strong>. <br> Je suis de plus en plus persuadé qu'il faut faire ce qu'on veut faire quand on veut le faire et ne pas chercher plus compliqué ! <br>Une citation ? <br><strong>"On ne repousse pas ses limites, on les découvre"</strong>, <i>Jean-Louis Etienne</i> </p>
				</div>
				<div class="celine member col-md-6">
					<div class="image-team">
						<%= cl_image_tag("Viivan/image-removebg-preview_21.png",:transformation=>[{:raw_transformation=> "w_300"}]) %>
					</div>
					<h4>Céline Devinoy</h4>
					<p>J'ai pas l’air comme ça, mais je suis de nature enthousiaste, surtout quand il s’agit de partir en voyage et de produire tout effort physique imaginable, tout en apprenant et en rencontrant.
Partir à l’aventure avec le <strong>beau Baptiste</strong>, c’est pratique parce qu’il rattrape toutes mes maladresses, mais c’est surtout que du bonheur et de l’amour au quotidien !
<br>Passionnée de couchers de soleil et de paysages plein de couleurs, je m’émerveille rapidement de chaque recoin de notre France...</p>
				</div>
				<div class="elvis member offset-md-3 col-md-6">
					<div class="image-team">
						<%= cl_image_tag("Viivan/image-removebg-preview_22.png",:transformation=>[{:raw_transformation=> "w_300"}]) %>
					</div>
					<h4>Elvis</h4>
					<p>C25, 30 ans, 240 000kms, moteur diesel, 3t5, 4m de long et 2,8m de haut ! J'ai beaucoup de chance d'être piloté par Céline et Baptiste qui prennent bien soin de moi et me font voir les plus beaux paysages ! Depuis que je suis avec eux j'ai été rénové, repeint, briqué on a changé ma courroie, <strong>bref je suis chouchouté quelle chance !</strong></p>
				</div>


			</div>

      <div class="row">
        <div class="member col-md-4">
          <div class="image-team">
              <%= cl_image_tag("https://res.cloudinary.com/dxjrnyrcp/image/upload/v1619884543/viivan%20compress%C3%A9/Fichier_3Poules-min.png",:transformation=>[{:raw_transformation=> "w_300"}]) %>
          </div>
          <h4>Michèle</h4>
          <p>La digne héritière des dinnosaures. Michèle est la patronne, elle règne sur la bassecour ! Mais elle sait être tendre et câline. L'oeuf qu'elle nous pond presque tous les jours est un pur délice ! </p>
        </div>
        <div class="member col-md-4">
          <div class="image-team">
              <%= cl_image_tag("https://res.cloudinary.com/dxjrnyrcp/image/upload/v1619884543/viivan%20compress%C3%A9/Fichier_4Poules-min.png",:transformation=>[{:raw_transformation=> "w_300"}]) %>
          </div>
          <h4>Jeanine</h4>
          <p>Petit ange parti trop tôt. Jeanine nous a apporté toute sa sympathie, ses courses délirantes, ses acrobaties. Ses oeufs en forme de Menhir nous manquent beaucoup ! </p>
        </div>
        <div class="member col-md-4">
          <div class="image-team">
              <%= cl_image_tag("https://res.cloudinary.com/dxjrnyrcp/image/upload/v1619885449/viivan%20compress%C3%A9/Germaine-min_1.png",:transformation=>[{:raw_transformation=> "w_300"}]) %>
          </div>
          <h4>Germaine</h4>
          <p>La mignonne petite nouvelle. Libérée des serres d'un coq de 6 fois sa taille chez Jardiland, Germaine redécouvre les petits plaisirs de la vie. Son élégance embellit nos journées !</p>
        </div>
      </div>
		</div>

	</div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg" id="navbar">
	<%= link_to root_path, class: "logo" do %>
    	<%= image_tag("viivan.gif", :class => "viivan-gif-navbar") %>
  	<% end %>
      <div class="d-flex">
        <div class="compteur">
          <img class="oeuf-image" src="https://visuels.l214.com/animaux/poules/oeufs/oeuf-detoure.png" alt="">
          <p> <%= Oeuf.count %> oeufs</p>
        </div>

      </div>


	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"><svg class="bi bi-list" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
		<path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
		</svg></span>
	</button>
<!-- 	<div class="nav-list row">
		<div class="nav-item"><a href="#demarche"> La démarche</a></div>
		<div class="nav-item">Ressources</div>
		<div class="nav-item"><a href="#sondage">Répondre au questionnaire</a></div>
		<div class="nav-item">Résultats</div>
		<div class="nav-item"><a href="#team">L'équipe</a></div>
	</div> -->
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav">
			<!-- <div class="nav-item"><a href="#demarche"> La démarche</a></div> -->

			<%= link_to "Suivez-nous !", root_path(anchor: 'suivez-nous'), class: 'nav-item' %>
			<%= link_to "Vos suggestions", root_path(anchor: 'suggestions'), class: 'nav-item'  %>
      <%= link_to "Galerie", galeries_path , class: 'nav-item' %>
			<%= link_to "Videos", videos_path , class: 'nav-item' %>
			<%= link_to "Nos petites histoires", articles_path, class: 'nav-item'%>

			<!-- <div class="nav-item"><a href="#team">L'équipe</a></div> -->
		</ul>
	</div>
</div>

app/views/suggestions/create.html.erb
<h1>Suggestions#create</h1>
<p>Find me in app/views/suggestions/create.html.erb</p>